routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::resource('press', 'PressReleaseController')->only([
    'index', 'show'
]);

Route::resource('directors', 'DirectorController')->only([
    'index', 'show'
]);

Route::get('about', 'AboutController@index')->name('about');

Route::get('faqs', 'FaqController@index')->name('faqs');

Route::resource('contact', 'ContactController')->only([
    'create', 'store'
]);

Route::resource('news', 'NewsController')->only([
    'index', 'show'
]);

Route::get('donate', 'DonateController@index')->name('donate');
Route::post('send-donation', 'DonateController@donate')->name('send-donation');

Route::resource('learning-resources', 'LearningResourceController')->only([
    'index', 'show'
]);

resources/views/includes/footer.blade.php
<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <h5>Useful Links</h5>
                <ul class="nav flex-column">
                    <li><a href="{{ route('home') }}">Home</a></li>
                    <li><a href="{{ route('press.index') }}">Press</a></li>
                    <li><a href="{{ route('about') }}">About</a></li>
                    <li><a href="{{ route('directors.index') }}">Directors</a></li>
                    <li><a href="{{ route('contact.create') }}">Contact Us</a></li>
                </ul>
            </div>            
            <div class="col-lg-3">
                <h5>Recent Press</h5>
                <ul class="nav flex-column">
                    @foreach($footer_press_releases as $press)
                        <li><a href="{{ route('press.show', $press->id) }}">{{ $press->title }}</a></li>
                    @endforeach
                </ul>
            </div>
            <div class="col-lg-3  social-links">
                <h5>Follow Us</h5>
                <p>Stay in touch and see the latest from Drinkers Voice</p>
                <ul class="nav">
                   <li><a href="https://www.facebook.com/DrinkersVoiceUK/"><i class="fab fa-facebook-f"></i></a></li>
                   <li><a href="https://twitter.com/DrinkersVoiceUK"><i class="fab fa-twitter"></i></a></li>
                </ul>
            </div>
            <div class="col-lg-3">
                <h5>Get In Touch</h5>
                <ul class="nav flex-column">
                    <li><a href="#">voice@drinkersvoice.org.uk</a></li>
                </ul>
            </div>

            <a href="#" class="back-to-top"><i class="fas fa-chevron-circle-up"></i>
                <br/>Back to <br/>top
            </a>
        </div>
    </div>

   
    <div class="terms">
        <div class="container">
            <div class="row">
                <div class="col-lg-9">
                    <ul>
                        <li class="copyright"> &copy; Copyright Drinkers Voice {{ date('Y') }}</li>
                        <li><a href="#" class="nav-link">Terms &amp; Conditions</a></li>
                        <li><a href="#" class="nav-link">Privacy Policy</a></li>              
                    </ul>
                </div>

                <div class="col-lg-3">
                    <a href="/"><img src="{{ asset('img/drinkersvoice-white.png') }}" class="footer-logo" /></a>
                </div>
            </div>
        </div>
    </div>
</footer>

resources/views/includes/header.blade.php
<header class="header">
    <div class="container">
        <a href="{{ route('home') }}">
            <img src="{{ asset('img/drinkersvoice.png') }}" class="logo" alt="drinkers voice"/>
        </a>
            
        <nav class="main-nav">
            <li>
                <li class="nav-item"><a class="nav-link" href="{{ route('home') }}">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="{{ route('about') }}">About</a></li>
                <li class="nav-item"><a class="nav-link" href="{{ route('faqs') }}">FAQs</a></li>
                <li class="nav-item"><a class="nav-link" href="{{ route('press.index') }}">Press</a></li>
                <li class="nav-item">
                    <a class="nav-link" href="#">People <i class="material-icons desktop-dropdown-icon">keyboard_arrow_down</i></a>
                    <ul>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('directors.index') }}">Directors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('directors.index') }}">Spokespeople</a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item"><a class="nav-link" href="{{ route('contact.create') }}">Contact Us</a></li>
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">
                            <i class="material-icons">person</i>
                            {{ __('Login') }}
                            <i class="material-icons desktop-dropdown-icon">keyboard_arrow_down</i>
                        </a> 
                        @if (Route::has('register'))
                        <ul>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">
                                    <i class="material-icons">person_add</i>
                                    {{ __('Register') }}
                                </a>
                            </li>
                        </ul>
                        
                    @endif
                    </li>
                @else
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="material-icons">person</i>
                            {{ Auth::user()->name }} <i class="material-icons desktop-dropdown-icon">keyboard_arrow_down</i>
                        </a>
                        <ul>
                            <li class="nav-item"><a class="nav-link" href="#" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                                <i class="material-icons">exit_to_app</i>
                                Logout</a></li>
                        </ul>
                        
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </li>
                @endguest
                <li class="nav-item highlight-nav"><a class="nav-link" href="{{ route('donate') }}">Donate</a></li>
            </ul>
        </nav>
        
        <span id="moby-button">
            <i class="material-icons">menu</i> 
            Menu
        </span>

    </div>
</header>

resources/views/includes/second-nav.blade.php
{{--<div class="second-nav">--}}
{{--    <div class="container">--}}
{{--        <ul>--}}
{{--            <li>--}}
{{--                Facts <i class="material-icons desktop-dropdown-icon">keyboard_arrow_down</i>--}}

{{--                <div class="sub-list">--}}
{{--                    <a href="#" class="sub-list-item">--}}
{{--                        <img src="https://picsum.photos/100/100" alt="">--}}
{{--                        <span>Alcoholic drinks and unit</span>--}}
{{--                    </a>--}}
{{--                    <a href="#" class="sub-list-item">--}}
{{--                        <img src="https://picsum.photos/100/100" alt="">--}}
{{--                        <span>Health effects of Alcohol</span>--}}
{{--                    </a>--}}
{{--                    <a href="#" class="sub-list-item">--}}
{{--                        <img src="https://picsum.photos/100/100" alt="">--}}
{{--                        <span>Drinking habits and behaviors</span>--}}
{{--                    </a>--}}
{{--                    <a href="#" class="sub-list-item">--}}
{{--                        <img src="https://picsum.photos/100/100" alt="">--}}
{{--                        <span>Alcohol and the law</span>--}}
{{--                    </a>--}}
{{--                    <a href="#" class="sub-list-item">--}}
{{--                        <img src="https://picsum.photos/100/100" alt="">--}}
{{--                        <span>How Alcohol affects relationships</span>--}}
{{--                    </a>--}}
{{--                </div>--}}
{{--            </li>--}}
{{--            <li>--}}
{{--                Advice <i class="material-icons desktop-dropdown-icon">keyboard_arrow_down</i>--}}
{{--            </li>--}}
{{--            <li>--}}
{{--                Tools <i class="material-icons desktop-dropdown-icon">keyboard_arrow_down</i>--}}
{{--            </li>--}}
{{--        </ul>--}}
{{--    </div>--}}
{{--</div>--}}